import { Grammar } from ".";

const accountsChoices = ["Avian (GB) - Avian.io - GA4"];
const fieldsChoices = [
  '"Active Users"',
  '"Shipping amount"',
  '"7-day active users"',
  '"Items purchased"',
  '"Session conversion rate"',
  '"Conversions Count For Chatgpt Plugin Install (Avian.io - GA4)"',
  '"Item-list view events"',
  '"Session conversion rate for purchase"',
  '"Average session duration"',
  '"Publisher ad clicks"',
  '"Ads cost per click (CPC)"',
  '"First-time purchasers per new user"',
  '"Transactions per purchaser"',
  '"Event count"',
  '"User engagement"',
  '"Event value"',
  '"ARPU"',
  '"Tax amount"',
  '"Organic google search clicks"',
  '"Views per user"',
  '"Add to carts"',
  '"Cart-to-view rate"',
  '"Ads impressions"',
  '"Checkouts"',
  '"Purchase revenue"',
  '"Organic google search average position"',
  '"Items checked out"',
  '"DAU per WAU"',
  '"First-time purchaser conversion"',
  '"Conversions count for purchase"',
  '"Items clicked in list"',
  '"Average Purchase Revenue Per Paying User (ARPPU)"',
  '"Item revenue"',
  '"Items viewed in promotion"',
  '"Organic google search click through rate"',
  '"First time purchasers"',
  '"Total purchasers"',
  '"User Conversion Rate For Chatgpt Plugin Install (Avian.io - GA4)"',
  '"Event count per user"',
  '"Purchase-to-view rate"',
  '"Bounce rate"',
  '"Crash-affected users"',
  '"Engagement rate"',
  '"Transactions"',
  '"User conversion rate"',
  '"Item view events"',
  '"Cohort active users"',
  '"Cost per conversion"',
  '"Ecommerce purchases"',
  '"Average Purchase Revenue Per User (All users)"',
  '"Ads clicks"',
  '"Organic google search impressions"',
  '"Engaged sessions"',
  '"Cohort total users"',
  '"Items viewed"',
  '"Total revenue"',
  '"User conversion rate for purchase"',
  '"Sessions"',
  '"Total users"',
  '"Items clicked in promotion"',
  '"Items added to cart"',
  '"Total ad revenue"',
  '"Average purchase revenue"',
  '"Ad unit exposure"',
  '"Views per session"',
  '"Session Conversion Rate For Chatgpt Plugin Install (Avian.io - GA4)"',
  '"Scrolled users"',
  '"Promotion clicks"',
  '"Sessions per user"',
  '"New users"',
  '"Return on ad spend"',
  '"DAU per MAU"',
  '"Publisher ad impressions"',
  '"Page views"',
  '"Promotion views"',
  '"Item-list click events"',
  '"Conversions"',
  '"28-day active users"',
  '"WAU per MAU"',
  '"Purchaser conversion"',
  '"Ads cost"',
  '"Session Google Ads campaign"',
  '"Google Ads account name"',
  '"Session medium"',
  '"Link classes"',
  '"Session Google Ads ad network type"',
  '"Session source platform"',
  '"Achievement ID"',
  '"Click / Link / Button Text"',
  '"Test data filter ID"',
  '"Page title and screen name"',
  '"Item category 4"',
  '"Video title"',
  '"Nth Week"',
  '"Session SA360 medium"',
  '"Session Google Ads campaign ID"',
  '"Nth Hour"',
  '"Page path"',
  '"Nth day"',
  '"Session Google Ads query"',
  '"Google Ads ad group ID"',
  '"First user Google Ads keyword text"',
  '"Google Ads campaign ID"',
  '"Browser"',
  '"Language code"',
  '"Session Google Ads Ad-Group Name"',
  '"Language"',
  '"Page path and screen class"',
  '"Full page URL"',
  '"Hour"',
  '"Month Name"',
  '"Link domain"',
  '"Quarter"',
  '"Session Google Ads Ad-Group ID"',
  '"First Session Date"',
  '"City ID"',
  '"Item category 3"',
  '"Item affiliation"',
  '"Google Ads campaign type"',
  '"Platform and Device Category"',
  '"Signed in with user ID"',
  '"First user Google Ads customer ID"',
  '"Content group"',
  '"Session Google Ads campaign type"',
  '"App Device model"',
  '"New or Returning User"',
  '"Year"',
  '"Page URL path"',
  '"Interests"',
  '"Session SA360 campaign"',
  '"Test data filter name"',
  '"Audience ID"',
  '"Audience name"',
  '"Session SA360 campaign ID"',
  '"Event Label (Avian.io - GA4)"',
  '"First user source And Medium"',
  '"Session source"',
  '"Item promotion name"',
  '"Content type"',
  '"Session Google Ads keyword text"',
  '"First user manual term"',
  '"First user Google Ads ad network type"',
  '"Session SA360 query"',
  '"Year Quarter"',
  '"Item brand"',
  '"Search term"',
  '"Device brand"',
  '"Country Code"',
  '"Day of Week (ISO)"',
  '"Day of Week"',
  '"Event Category (Avian.io - GA4)"',
  '"Country Name"',
  '"Google Ads keyword text"',
  '"App version"',
  '"Campaign ID"',
  '"Item promotion creative name"',
  '"First user default channel group"',
  '"City"',
  '"Device category"',
  '"Transaction ID"',
  '"Ad format"',
  '"Content ID"',
  '"First user Google Ads account name"',
  '"Video URL"',
  '"First user manual ad content"',
  '"File name"',
  '"Google Ads creative ID"',
  '"Nth Month"',
  '"Page referrer"',
  '"Session Campaign Name"',
  '"Session manual term"',
  '"Ad unit"',
  '"Session SA360 keyword text"',
  '"Session Google Ads Account Name"',
  '"Manual ad content"',
  '"Minute"',
  '"Page title"',
  '"Operating system"',
  '"Order coupon"',
  '"Visible"',
  '"Session SA360 engine account type"',
  '"Google Ads customer ID"',
  '"Link ID"',
  '"Session manual ad content"',
  '"Operating system with version"',
  '"Protocol + hostname + page path + query string"',
  '"OS version"',
  '"Event name"',
  '"First user source"',
  '"First user Google Ads creative ID"',
  '"First user medium"',
  '"First user campaign"',
  '"First user source platform"',
  '"Week"',
  '"Continent ID"',
  '"Link URL"',
  '"Page title and screen class"',
  '"Item ID"',
  '"Item category"',
  '"Ad source"',
  '"Item promotion ID"',
  '"Nth Year"',
  '"Session Campaign ID"',
  '"Date"',
  '"First user Google Ads ad group ID"',
  '"Item list ID"',
  '"Group ID"',
  '"Session Default Channel Group"',
  '"Page URL path + query string"',
  '"Platform"',
  '"Character"',
  '"Google Ads query"',
  '"Session Google Ads customer ID"',
  '"Item category 2"',
  '"First user Google Ads campaign type"',
  '"Session SA360 creative format"',
  '"Item name"',
  '"Mobile Device Name"',
  '"File extension"',
  '"Session SA360 engine account ID"',
  '"Continent Name"',
  '"Virtual currency name"',
  '"Level"',
  '"Percent scrolled"',
  '"Cohort Name"',
  '"Google Ads ad network type"',
  '"Landing page URL"',
  '"Item variant"',
  '"Day of Year"',
  '"First user Google Ads ad group name"',
  '"Stream ID"',
  '"Session SA360 engine account name"',
  '"Session Source And Medium"',
  '"Is conversion event"',
  '"Google Ads ad group name"',
  '"Property name"',
  '"Shipping tier"',
  '"Year Week"',
  '"Google Ads campaign"',
  '"First user Google Ads query"',
  '"Session SA360 ad group name"',
  '"Region"',
  '"Age"',
  '"Method"',
  '"Click Text (Avian.io - GA4)"',
  '"Item list name"',
  '"Video provider"',
  '"Month"',
  '"Hostname"',
  '"First user campaign ID"',
  '"Year Month"',
  '"First user Google Ads campaign ID"',
  '"Item category 5"',
  '"Session SA360 source"',
  '"Screen resolution"',
  '"Campaign"',
  '"Session Google Ads creative ID"',
  '"First user Google Ads campaign"',
  '"Manual term"',
  '"Mobile model"',
  '"Nth Minute"',
  '"Outbound"',
  '"Gender"',
];

const KingGrammar = new Grammar({ debug: true })
  .define("simpleString", (r) => r.sequence('"', r.range('[^\\n"]+'), '"'))
  .define("boolean", (r) => r.oneOf("true", "false"))
  .define("singleDigit", (r) => r.range("[0-9]"))
  .define("nonZeroDigit", (r) => r.range("[1-9]"))
  .define("dateYear", (r) => r.sequence(r.oneOf("19", "20"), r.ref("singleDigit"), r.ref("singleDigit")))
  .define("dateMonth", (r) => r.oneOf(r.sequence("0", r.ref("singleDigit")), "11", "12"))
  .define("dateDay", (r) =>
    r.oneOf(r.sequence("0", r.ref("nonZeroDigit")), r.sequence(r.oneOf("1", "2"), r.ref("singleDigit")), "30", "31")
  )
  .define("date", (r) => r.sequence('"', r.ref("dateYear"), "-", r.ref("dateMonth"), "-", r.ref("dateDay"), '"'))
  .define("accountsChoices", (r) => r.oneOf(...accountsChoices))
  .define("fieldsChoices", (r) => r.oneOf(...fieldsChoices))
  .define("accountsField", (r) =>
    r.sequence(
      '"accounts": [\n',
      r.ref("accountsChoices"),
      r.zeroOrMore(r.sequence(", ", r.ref("accountsChoices"))),
      "],\\n"
    )
  )
  .define("endDateField", (r) => r.sequence('"end_date": ', r.ref("date"), ",\\n"))
  .define("fieldsField", (r) =>
    r.sequence('"fields": [', r.ref("fieldsChoices"), r.zeroOrMore(r.sequence(", ", r.ref("fieldsChoices"))), "],\\n")
  )
  .define("filterField", (r) =>
    r.optional(
      r.sequence('"filter": [', r.ref("simpleString"), r.zeroOrMore(r.sequence(", ", r.ref("simpleString"))), "],\\n")
    )
  )
  .define("previousPeriodField", (r) => r.optional(r.sequence('"previous_period": ', r.ref("boolean"), ",\\n")))
  .define("sortField", (r) =>
    r.optional(
      r.sequence('"sort": [', r.ref("simpleString"), r.zeroOrMore(r.sequence(", ", r.ref("simpleString"))), "],\\n")
    )
  )
  .define("startDateField", (r) => r.sequence('"start_date": ', r.ref("date"), "\\n"))
  .define("json", (r) =>
    r.sequence(
      "{\\n",
      r.ref("accountsField"),
      r.ref("endDateField"),
      r.ref("fieldsField"),
      r.ref("filterField"),
      r.ref("previousPeriodField"),
      r.ref("sortField"),
      r.ref("startDateField"),
      "\\n}"
    )
  )
  .root("json");
